### PR TITLE
Featurepatch

### PR DESCRIPTION
**Pull request by roshankcjha**
Added Python scripts for :
1)Displaying top trending IT news from hackernews
2)Automating process of sending emails to large number of people.

### CODE REVIEW

**Comment by amandp13** [comment]
@roshankcjha Can you please put it in a folder with the README.md file in it so that it would be clear what the script is all about.

**Comment by roshankcjha** [comment]
Hey @amandp13 can you provide some sample READMEs in order to get familiar with what exactly I must mention about the respective Python Scripts?I will start working on it immediately now in order to get the best results

**Comment by amandp13** [comment]
@roshankcjha as Simple as it can be, Check https://github.com/amandp13/Cool-Scripts-Python-Nerds/tree/master/Images_Downloader

**Comment by roshankcjha** [comment]
Hey @amandp13  do check out PR #48 it has the updated code with info about the scripts attached.

**Pull request closed without merging**
