### PR TITLE
caesear

### PR DESCRIPTION
**Pull request by jessicajon**
Through this python module, thr user will be able to encrypt their text. This program prompts the user for the number which is used to chose the alphabet for encryption.

### CODE REVIEW

**Comment by amandp13** [comment]
@jessicajon Hey! Can you please put it in a folder with the README.md file in it so that it would be clear what the script is all about, DM if need any help.

**Comment by jessicajon** [comment]
> @jessicajon Hey! Can you please put it in a folder with the README.md file in it so that it would be clear what the script is all about, DM if need any help.

I have updated the PR and made changes as told

**Comment by amandp13** [comment]
@jessicajon Cool, But you left the old script in the Repository, do check once and delete that commit. 😊

**Comment by amandp13** [comment]
Good to go

**Pull request merged**
