### PR TITLE
python password example

### PR DESCRIPTION
**Pull request by farihaNaqvi**

### CODE REVIEW

**Comment by farihaNaqvi** [comment]
can u merge it?

**Comment by amandp13** [comment]
@farihaNaqvi Yeah sure, But can you please put it in a folder with the README.md file in it, so that it would be clear what the script is all about.

**Comment by farihaNaqvi** [comment]
sir done

**Comment by farihaNaqvi** [comment]
sir, can u merge it now??

**Comment by amandp13** [comment]
@farihaNaqvi Cool.

**Pull request merged**
